## 2025 State of the Ecosystem Request tracking memo: updates noted along the way

Need to add the files

```{r, results='hide', eval = FALSE}
## TODO: access this file from network drive?? or download into repo
 requests <- read.csv(here::here("SOE prioritization worksheet.csv"))
```

```{r memo, eval = FALSE}

# requests <- googledrive::drive_download(resultfile, type = "csv", overwrite = TRUE) %>%
#   {read.csv(.$local_path)} 

requeststab <- requests %>%
  dplyr::select(Request, Year, Aggregate = Aggregate.Category, Project, Source, Status, Progress, Order) %>%
  dplyr::mutate(Source = str_trim(str_extract(Source, "[^-]+"))) %>%
  dplyr::group_by(factor(Aggregate, levels = c("System level thresholds/ref pts",
                                               "Management",
                                               "Short term forecasts",
                                               "Regime shifts",
                                               "Multiple system drivers",
                                               "Functional group level status/thresholds/ref pts",
                                               "Stock level indicators",
                                               "SOE admin"))
                  )%>% #, Project) %>%
  dplyr::mutate(#AvgOrder = mean(Order, na.rm=T),
                Rank = factor(case_when(Order < 1.5 ~ "Highest", 
                                     Order >= 1.5 & Order < 1.75 ~ "High",
                                     Order >= 1.75 & Order < 2 ~ "Moderate",
                                     Order >= 2 & Order < 2.5 ~ "Low",
                                     Order >=2.5 ~ "Lowest",
                                     TRUE ~ "Unranked"),
                       levels=c("Highest", "High", "Moderate", "Unranked", "Low", "Lowest")))%>%
  dplyr::arrange(Rank, Order, .by_group = TRUE) %>% #AvgOrder, 
  # arrange(match(Status, c("In SOE", 
  #                         "In SOE-MAFMC",
  #                         "In SOE-MAFMC, In progress-NEFMC",
  #                         "In progress", 
  #                         "Not started")), desc(Year)) %>%
  dplyr::ungroup() %>%
  #dplyr::mutate("Memo Section" = rownames(.)) %>%
  #dplyr::mutate(Section = dplyr::group_indices(.)) %>%
  dplyr::select(Request, Year, Aggregate, Rank, Source, Status, Progress)

flextable::as_grouped_data(requeststab, groups = "Aggregate") %>% 
  flextable::as_flextable(hide_grouplabel=TRUE) %>% 
  flextable::align(i = ~ !is.na(Aggregate), align = "left") %>% 
  flextable::bold(i = ~ !is.na(Aggregate), bold = TRUE) %>%
  flextable::theme_zebra() %>%
  flextable::bg(i = ~ !is.na(Aggregate), bg = "beige", part = "body") %>%
  flextable::hline(i = ~ !is.na(Aggregate)) %>%
  #flextable::set_caption("State of the Ecosystem requests by category and Council priority.") %>%
  flextable::autofit() 
  #flextable::width(width = c(2.5,0.5,0.7,0.7,0.7,1.5))

```

